blogapp/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage),
    path('about/', views.aboutpage),
    path('contact/', views.contactpage),
    path('signup/', views.signup, name='signup'),
    path('login/', views.userlogin, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.userlogout, name='logout'),
    path('addpost/', views.addpost, name='add'),
    path('updatepost/<int:id>', views.updatepost, name='update'),
    path('deletepost/<int:id>', views.deletepost, name='delete'),
    path('editprofile/<int:id>', views.editprofile, name='editprofile'),
]

blogapp/blogapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

blogapp/blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    author= models.CharField(max_length= 150)
    title= models.CharField(max_length= 150)
    description= models.TextField()
    
class PostwithImage(models.Model):
    author= models.CharField(max_length= 150)
    title= models.CharField(max_length= 150)
    description= models.TextField()
    blog_image= models.ImageField(upload_to='blogimg')

    

blogapp/blog/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, UserChangeForm
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from .models import Post
class SignupForm(UserCreationForm):
    password1= forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2= forms.CharField(label='Confirm Password(Again)', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model= User
        fields= ['username', 'first_name', 'last_name', 'email']
        labels= {'first_name':'First Name', 'last_name':'Last Name', 'email': 'Email'}
        widgets= {
            'username':forms.TextInput(attrs={'class': 'form-control'}),
            'first_name':forms.TextInput(attrs={'class': 'form-control'}),
            'last_name':forms.TextInput(attrs={'class': 'form-control'}),
            'email':forms.EmailInput(attrs={'class': 'form-control'}),
            }
        
class LoginForm(AuthenticationForm):
    username= UsernameField(widget=forms.TextInput(attrs={'class':'form-control'}))
    password= forms.CharField(label=_('Password'), strip=False, widget=forms.PasswordInput( attrs={'class':'form-control', 'autocomplete': 'current-password'}))
    

class PostForm(forms.ModelForm):
    class Meta:
        model= Post
        fields= ['author','title', 'description' ]
        widgets= {
            'author':forms.TextInput(attrs={'class': 'form-control'}), 
            'title':forms.TextInput(attrs={'class': 'form-control'}),
            'description':forms.Textarea(attrs={'class': 'form-control'}),
        }

class EditUserProfileForm(UserChangeForm):
    password= None;
    class Meta:
        model= User
        fields=['username','first_name','last_name','email']
        label= {'email':'Email'}  # i change email lebel bocoz it bydefault print email Address
        widgets= {
            'username':forms.TextInput(attrs={'class': 'form-control'}), 
            'first_name':forms.TextInput(attrs={'class': 'form-control'}),
            'last_name':forms.TextInput(attrs={'class': 'form-control'}),
            'email':forms.EmailInput(attrs={'class': 'form-control'}),
            
        }
        

blogapp/blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Post
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import PostForm
from django.contrib.auth.models import User, Group
from . import forms


def homepage(request):
    postdata= Post.objects.all()
    return render(request, 'blog/home.html', {'data':postdata})
def aboutpage(request):
    return render(request, 'blog/about.html')
def contactpage(request):
    return render(request, 'blog/contact.html')

def dashboard(request):
    if request.user.is_authenticated:
        posts= Post.objects.all()
        fullname= request.user.get_full_name()
        user= User.objects.filter(username= request.user)
        print(user)
        return render(request, 'blog/dashboard.html', {'post':posts, 'user':user, 'fullname':fullname} )
    else:
        return HttpResponseRedirect('/login/')

def signup(request):
    if request.method== 'POST':
        fm= forms.SignupForm(request.POST)
        if fm.is_valid():
            messages.success(request, 'Congratulation! You are now Author😎')
            user= fm.save()
            group= Group.objects.get(name='Author')
            user.groups.add(group)
            fm= forms.SignupForm()
            return HttpResponseRedirect('/login/')
    else:
        fm= forms.SignupForm()
    return render(request, 'blog/signup.html', {'form':fm})

def userlogin(request):
    if not request.user.is_authenticated:
        if request.method== 'POST':
            fm= forms.LoginForm(request=request,  data=request.POST)
            if fm.is_valid():
                uname= fm.cleaned_data['username']
                upass= fm.cleaned_data['password']
                user= authenticate(username= uname, password=upass)
                if user is not None:
                    login(request, user)
                    messages.success(request, 'Logged in Successfully ')
                    return HttpResponseRedirect('/dashboard/')
        else:  
            fm= forms.LoginForm()
        return render(request, 'blog/login.html', {'form':fm})
    else:
        return HttpResponseRedirect('/dashboard/')
def userlogout(request):
    logout(request)
    return HttpResponseRedirect("/login/")

# Add New Post
def addpost(request):
    if  request.user.is_authenticated:
        if request.method== 'POST':
            fm= PostForm(request.POST)
            if fm.is_valid():
                messages.success(request, "Blog Posted Successfully😎")
                fm.save()
                fm=PostForm()
        else:
            fm=PostForm()
        return render(request, 'blog/addpost.html', {'form':fm})
    else:
        return HttpResponseRedirect('/login/')
    
# Update the existing post
def updatepost(request, id):
    if  request.user.is_authenticated:
        if request.method=='POST':
            data= Post.objects.get(pk=id)
            fm= PostForm(request.POST, instance=data)
            if fm.is_valid():
                messages.success(request, "Blog Updated Successfully😎")
                fm.save()
                return HttpResponseRedirect('/dashboard/')
        data= Post.objects.get(pk=id)
        fm= PostForm(instance=data)
        return render(request, 'blog/updatepost.html',{'form':fm})
    else:
        return HttpResponseRedirect('/login/')
    
# Delete the existing post
def deletepost(request, id):
    if  request.user.is_authenticated:
        if request.method=='POST':
            datafordelete= Post.objects.get(pk=id) 
            datafordelete.delete()
        return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/login/')
    
    
def editprofile(request , id):
    if  request.user.is_authenticated:
        if request.method=='POST':
            data= User.objects.get(pk=id)
            fm= forms.EditUserProfileForm(request.POST, instance= data)
            if fm.is_valid():
                messages.success(request, "Profile Updated Successfully")
                fm.save()
                return HttpResponseRedirect('/dashboard/')
        else:
            data= User.objects.get(pk=id)
            fm= forms.EditUserProfileForm(instance=data)
        return render(request, 'blog/editprofile.html', {'form':fm})
    else:
        return HttpResponseRedirect('/login/')

    

blogapp/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
    <div class="col-sm-10">
        <h3 class=' m-3'>About Page</h3>
        <div class='jumbotron '>

            <h3>this is About page</h3>
            <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae praesentium aperiam nisi sint ipsam provident possimus aliquam accusamus iste ab recusandae enim dolorem, voluptates consectetur illum inventore rem, nihil deserunt porro. Voluptas sequi, in aperiam provident quidem quibusdam excepturi enim sint labore explicabo expedita illo cum harum repellat ea impedit aliquid! Blanditiis, suscipit. Dolore, ab excepturi?</p>
        </div>
    </div>

{% endblock content %}

blogapp/blog/templates/blog/addpost.html
{% extends "blog/base.html" %}
{% load static %}





{% block content %}

{% if messages %}
    {% for msg in messages %}
    <div {% if msg %} class="alert alert-{{msg.tags}} alert-dismissible fade show text-center" {% endif %} role="alert">
        <strong> {{msg}} </strong> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
{% endif %}



{% for err in form.non_field_errors %}
<p class='alert alert-danger'> {{err}} </p>
{% endfor %}
    <div class='col-sm-8 mx-auto shadow my-4 p-0 border'>
        <div class='h4 form-header mx-0 p-4 text-center text-white'>Dashboard / New Post</div>
        <form  class='px-5' method='POST' novalidate >
            {% csrf_token %}
            {% for fm in form %}
            <div class="form-group text-white">
                {{fm.label_tag}} {{fm}} <small class='text-warning'>{{fm.errors|striptags}}</small><br> 
            </div>
            {% endfor %} 
            <div class='text-end px-3'>
                <input class='btn btn-dark mb-4' type="submit" value='Upload'>
            </div>
        </form>
    </div>
    <div class='text-center'>

        <a href='{% url "dashboard"  %}' class=' button-33'> Dashboard </a>
    </div>
{% endblock content %}

blogapp/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0-beta1/css/bootstrap.min.css" />


    <link rel="stylesheet" href="{% static "blog/css/bootstrap.min.css" %}">
    
    <link rel="stylesheet" href="{% static "blog/css/style.css" %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    
    <title>Blog App</title>
</head>
<body style='background-color:black;'>
    {% include "blog/navbar.html" %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block msg %}
                {% endblock msg %}
            </div>
        </div>
        <div class="row">
            {% block side %}
            {% endblock side %}

            {% block content %}
            {% endblock content %}

        </div>
    </div>
    {% block footer %}{% endblock  %}

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"></script>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>


    

</body>
</html>

blogapp/blog/templates/blog/contact.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
    <div class="col-sm-10">

        <form class=' border px-5 py-5 bg-dark my-3'>
            <div class='text-white h1 text-center '> Contact Info</div>
            <div class="row py-3">
              <div class="form-group col-sm-7">
                <label for="inputEmail4">Email</label>
                <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
              </div>
              <div class="form-group col-sm-4">
                <label for="inputPassword4">Password</label>
                <input type="password" class="form-control" id="inputPassword4" placeholder="Password">
              </div>
            </div><br>
            <div class='row'>
                <div class="form-group col-sm-6">
                    <label for="inputAddress">Address</label>
                    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
                </div>
                <div class="form-group col-sm-6">
                    <label for="inputAddress2">Address 2</label>
                    <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
                </div>
            </div><br>
            <div class="row">
              <div class="form-group col-md-6">
                <label for="inputCity">City</label>
                <input type="text" class="form-control" id="inputCity">
              </div>
              <div class="form-group col-md-4">
                <label for="inputState">State</label>
                <select id="inputState" class="form-control">
                  <option selected>Choose...</option>
                  <option>...</option>
                </select>
              </div>
              <div class="form-group col-md-2">
                <label for="inputZip">Zip</label>
                <input type="text" class="form-control" id="inputZip">
              </div>
            </div>
            <div class="form-group">
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck">
                <label class="form-check-label" for="gridCheck">
                  Check me out
                </label>
              </div>
            </div><br>
            <button type="submit" class="btn btn-primary">Sign in</button>
          </form>
    </div>
{% endblock content %}

blogapp/blog/templates/blog/dashboard.html
{% extends "blog/base.html" %}
{% load static %}



{% block msg %}

{% if messages %}

    {% for msg in messages %}

        <div {% if msg %}class="alert alert-{{msg.tags}} alert-dismissible fade show" {% endif %}  role="alert">
            <strong>{{msg}}</strong> 
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

    {% endfor %}
{% endif %}

{% endblock msg %}



{% block content %}
   
<div class='d-flex justify-content-evenly mt-3'>

    <p class="d-inline-flex gap-1">
        <a class="button-33" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
          Dashboard
        </a>
    </p>
    <a href="{% url "add" %}" class=' button-33  mb-3'>Add Post</a>
</div>
<div class="collapse" id="collapseExample">
            <div class="col-sm-12">
                {% comment %} <h3 class=' m-3'>Dashboard Page</h3> {% endcomment %}
                <h4 class='text-center alert-glass mt-3 text-white'>Show Post Information</h4>
                
        
                {% if post %}
                    <table class='table table-hover  table-dark table-bordered'>
                        <thead>
                            <tr class='text-center table-danger'>
                                <th scope='col' class='text-center' style='width:2%'>ID</th>
                                <th scope='col' class='text-center' style='width:5%'>Author</th>
                                <th scope='col' class='text-center' style='width:28%'>Title</th>
                                <th scope='col' class='text-center' style='width:50%'>Description</th>
                                <th scope='col' class='text-center' style='width:15%'>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for pst in post %}
                                <tr height='100px'>
                                    <td scope='row text-center'> {{pst.id}} </td>
                                    <td scope='row text-center'> {{pst.author}} </td>
                                    <td scope='row text-center'> {{pst.title}} </td>
                                    <td scope='row text-center'> {{pst.description}} </td>
                                    <td class='text-center'>
                                        <a href='{% url "update" pst.id %}' class='btn btn-primary btn-sm'>Edit</a>
        
                                        {% if perms.blog.delete_post %}
        
                                            <form action="{% url "delete" pst.id %}" class='d-inline' method='POST'>
                                                {% csrf_token %}
                                                <input type="submit" class='btn btn-danger btn-sm' value="Delete" id="">
                                            </form>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
    </div>
</div>

<div>
    <h4 class='alert-glass text-white'>Profile Details</h4>
        <div class='row '>
            <div class='col-sm-4 text-center '><img class='rounded-circle p-1  border' height='200' width='200'  src="{% static "blog/img/images.jpeg" %}" alt=""></div>
            <div class='col-sm-8'>


                <table class='table table-striped table-hover table-dark table-bordered'>
                    <tbody>
                        <tr>
                            <td>User Name: </td>
                            <td>{{ request.user }} </td>
                        </tr>
                            
                    
                        {% for u in user %}
                            <tr>
                                <td>User Id: </td>
                                <td>{{ u.id }} </td>
                            </tr>
                            <tr>
                                <td> First Name: </td>
                                <td>{{ u.first_name }} </td>
                            </tr>
                            <tr>
                                <td> Last Name: </td>
                                <td>{{ u.last_name }} </td>
                            </tr>
                            <tr>
                                <td> Email: </td>
                                <td>{{ u.email }} </td>
                            </tr>
                            <tr>
                                <td> Date of Joined: </td>
                                <td>{{ u.date_joined }} </td>
                            </tr>
                            <tr>
                                <td> Last Login: </td>
                                <td>{{ u.last_login }} </td>
                            </tr>
                            <tr>
                                <td> Edit Profile: </td>
                                <td> <span class='text-danger'>Edit </span> <a class=' link' href="{% url "editprofile" u.id %}"><span class='text-primary'>Profile</span></a> </td>
                            </tr>
                            <tr>
                                <td> Dashboard: </td>
                                <td> 
                                    
                                    <p class="d-inline-flex gap-1">
                                        <a class="button-33" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                                          Dashboard
                                        </a>
                                    </p>
                                
                                
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>

            </table>

                
                   

            </div>
            
        </div>

</div>


{% endblock content %}

blogapp/blog/templates/blog/editprofile.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}

{% if messages %}
    {% for msg in messages %}
    <div {% if msg %} class="alert alert-{{msg.tags}} alert-dismissible fade show text-center" {% endif %} role="alert">
        <strong> {{msg}} </strong> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
{% endif %}




{% for err in form.non_field_errors %}
    <p class='alert alert-danger'> {{err}} </p>
{% endfor %}
    <div class='col-sm-5 mx-auto shadow my-2 p-0 border'>
        <div class='h3 form-header mx-0 p-4 text-center text-white'>Update Profile</div>
        <form action="" method='POST' class='px-5  mt-5' novalidate>
            {% csrf_token %}
            {% for fm in form %}
            <div class="form-group text-white">
                {{fm.label_tag}} {{fm}}  <small class='text-warning'>{{fm.errors|striptags}}</small><br> 
            </div>
            {% endfor %} 
            <div class='text-end px-3'>
                <input class='btn btn-dark mb-4 glorish' style='margin-right: 50px;' type="submit" value='Submit'>
            </div>

            <div class='mb-4 mt-0 mx-4' >
                <span class='text-primary'>Existing user? </span> <a class='link text-danger' href='{% url "login" %}'>Login</a>
            </div>

        </form>
    </div>

{% endblock content %}

blogapp/blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}

  <div class='text-end mt-3'>
    <a href="{% url "add" %}" class=' button-33  mb-3'>Add Post</a>
  </div>

    <div class="col-sm-12">
        {% for data in data %}
        <div class="jumbotron jumbotron-fluid ">
            <div class="container">
              <h1 class='text-center heading mb-3'>{{data.title}}</h1>
              <p class="lead text-white">{{data.description}}</p>
              <div class='text-end fontt text-white'>author: {{data.author}}</div>
              <a href="{%  url 'update' data.id %}" class="button-33">Update</a>
            </div>
          </div>
          {% endfor %}

         

    </div>
{% endblock content %}

blogapp/blog/templates/blog/login.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
        
{% for err in form.non_field_errors %}
    <p class='alert alert-danger'> {{err}} </p>
{% endfor %}
    <div class='col-sm-5 mx-auto shadow my-4 p-0 border mt-5'>
        <div class='h3 form-header mx-0 p-4 text-center text-white '>Login</div>
        <form  class='px-5' method='POST' novalidate >
            {% csrf_token %}
            {% for fm in form %}
            <div class="form-group text-white">
                {{fm.label_tag}} {{fm}} <small class='text-warning'>{{fm.errors|striptags}}</small><br> 
            </div>
            {% endfor %} 
            <div class='text-end px-3'>
                <input class='btn btn-dark mb-4' type="submit" value='Submit'>
            </div>
            <div class='mb-4 mt-0 mx-4'>
                <span class='text-primary'>new user? </span> <a class='link text-danger' href='{% url "signup" %}'>Sign-up</a>
            </div>
        </form>
    </div>

{% endblock content %}

blogapp/blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navv">
    <a class="navbar-brand px-3 heading-logo text-white" href="#">My Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav px-3">
        <li class="nav-item px-2 ">
          <a class="nav-link text-white" href="/">Home </a>
        </li>

        
        {% if request.user.is_authenticated %}

          <li class="nav-item px-2">
            <a class="nav-link text-white" href="{% url "dashboard" %}">Profile</a>
          </li>
          <li class="nav-item px-2">
            <a class="nav-link text-white" href="{% url "logout" %}">Logout</a>
          </li>

          {% else %}

          <li class="nav-item px-2">
            <a class="nav-link text-white" href="/about">About</a>
          </li>
          <li class="nav-item px-2">
            <a class="nav-link text-white" href="/contact">Contact</a>
          </li>

        <li class="nav-item px-2 dropdown">
            <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Registration
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url "signup" %}">Signup</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url "login" %}">Login</a>
            </div>
        </li>

        
        
        {% endif %}

      </ul>
    </div>
  </nav>

blogapp/blog/templates/blog/signup.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}

{% if messages %}
    {% for msg in messages %}
    <div {% if msg %} class="alert alert-{{msg.tags}} alert-dismissible fade show text-center" {% endif %} role="alert">
        <strong> {{msg}} </strong> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
{% endif %}




{% for err in form.non_field_errors %}
    <p class='alert alert-danger'> {{err}} </p>
{% endfor %}
    <div class='col-sm-7 mx-auto shadow my-2 p-0 border'>
        <div class='h3 form-header mx-0 p-4 text-center text-white'>Sign-Up</div>
        <form action="" method='POST' class='px-5 ' novalidate>
            {% csrf_token %}
            {% for fm in form %}
            <div class="form-group text-white">
                {{fm.label_tag}} {{fm}}  <small class='text-warning'>{{fm.errors|striptags}}</small><br> 
            </div>
            {% endfor %} 
            <div class='text-end px-3'>
                <input class='btn btn-dark mb-4 glorish' type="submit" value='Submit'>
            </div>

            <div class='mb-4 mt-0 mx-4'>
                <span class='text-primary'>Existing user? </span> <a class='link text-danger' href='{% url "login" %}'>Login</a>
            </div>

        </form>
    </div>

{% endblock content %}

blogapp/blog/templates/blog/updatepost.html
{% extends "blog/base.html" %}
{% load static %}





{% block content %}

{% if messages %}
    {% for msg in messages %}
    <div {% if msg %} class="alert alert-{{msg.tags}} alert-dismissible fade show text-center" {% endif %} role="alert">
        <strong> {{msg}} </strong> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
{% endif %}



{% for err in form.non_field_errors %}
<p class='alert alert-danger'> {{err}} </p>
{% endfor %}
    <div class='col-sm-8 mx-auto shadow my-4 p-0 border'>
        <div class='h4 form-header mx-0 p-4 text-center text-white'>Dashboard / Update Post</div>
        <form  class='px-5' method='POST' novalidate >
            {% csrf_token %}
            {% for fm in form %}
            <div class="form-group text-white">
                {{fm.label_tag}} {{fm}} <small class='text-warning'>{{fm.errors|striptags}}</small><br> 
            </div>
            {% endfor %} 
            <div class='text-end px-3'>
                <input class='btn btn-dark mb-4' type="submit" value='Upload'>
            </div>
        </form>
    </div>
    <div class='text-center'>

        <a href='{% url "dashboard"  %}' class=' button-33'> Dashboard </a>
    </div>
{% endblock content %}